### ISSUE TITLE
"Migration Aborted" after the migration started

### ISSUE THREAD

**Issue by derek68** [ridaamirini/ImapSyncClient#5]
Hi All

Im trying to migrate and copy all emails from one server to the other server.

The first server is a linux mail server and the second is a windows mail server.

I know my username and password is correct as I can created the same  account using the email client thunderbird and it connects to mail servers.  Can someone please help with the error and let me know how it can be fixed.
---------------------------------------
Welcome to imapsync 
Version 0.0.1aa596fa
Migration started ...
Request to migrate (506@****.com.au => 506@****.com.au)
Started to migrate (506@****.com.au => 506@****.com.au) <=> 5af3c701c0110 [Emitted]
Migration aborted ...
Migration aborted ...

-----------------------------------------

Thanking you in advance.

**Comment by derek68** [comment]
Hi Rida

Do you know when you will have time to create a fix?

Regards

Derek

**Comment by ridaamirini** [comment]
Hey Derek,

i need to figure out where the problem is i think API has some issues.

**Comment by ridaamirini** [comment]
Can u pls update the ImapSync Client on [v0.0.3](https://github.com/ridaamirini/ImapSyncClient/releases/tag/v0.0.3) and then post the log.

By default it writes logs to the following locations:



 * **on Linux:** `~/.config/<app name>/log.log`

 * **on OS X:** `~/Library/Logs/<app name>/log.log`

 * **on Windows:** `%USERPROFILE%\AppData\Roaming\<app name>\log.log`

**Comment by derek68** [comment]
HI Rida

Thank you for the update. But it is doing the same thing.  I’m usining windows 10 and I’ve looked for the path and searched for the log, but I can find one?   

Regards

**Comment by ridaamirini** [comment]
Hello Derek,

i only added the logger. We need to get log. That i can figure out the issue.

Can u upload the folder where the log should be.

Regards

**Comment by derek68** [comment]
HI Radaa

I have found the log, sorry I could not find it yesterday.  I realy appreachate your help.

Regards
[log.log](https://github.com/ridaamirini/ImapSyncClient/files/1998091/log.log)

**Comment by ridaamirini** [comment]
@derek68 i think i fixed it. Can u check it for me pls?

**Comment by derek68** [comment]
Hi Rida

It is getting closer, but its still failing.  Ive tried three users and im sill getting the same issue. 

Ive attached the logs and screen print,

![capture](https://user-images.githubusercontent.com/22875102/39972832-131bba44-575a-11e8-8b66-a8fce364305c.JPG)
[log.log](https://github.com/ridaamirini/ImapSyncClient/files/1999040/log.log)

Regards

**Comment by derek68** [comment]
Hi Rada

Im inside of our network on our LAN and the IP address are internal.  Do I have to use our external IP address.

Once again thank you for helping, I sorry this has caused you so much trouble.

Regards

**Comment by ridaamirini** [comment]
Hi Derek,

u are welcome :+1: . Yes u need to give the external IP, so the API must reach it.

**Comment by derek68** [comment]
Hi Rada

Is there anyway of getting it change so its the internal IP address.  As im migrating from one server to the other with the same domain and same users.

Regards

**Comment by ridaamirini** [comment]
@derek68 No, because the ImapSync Client is using a API Server to get the job done.

But this tool [imapsync/imapsync](https://github.com/imapsync/imapsync) might solve ur problem. The API is based on it.

**Comment by derek68** [comment]
Hi Rada

Ok thought that might be the case.  I want to thank you for your time and effort.

Regards

**Comment by CasparMenke** [comment]
Hello Rada
I am trying to get your Software to work on Windows 10 but I always aborts.
Here is the log:

018-09-20 17:41:23:0395] [info] Update for version 0.0.4 is not available (latest version: 0.0.4, downgrade is disallowed).
[2018-09-20 17:41:54:0837] [error] Error: Request failed with status code 404
    at createError (C:\Users\my\AppData\Local\Programs\imapsyncclient\resources\app.asar\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\my\AppData\Local\Programs\imapsyncclient\resources\app.asar\node_modules\axios\lib\core\settle.js:18:12)
    at XMLHttpRequest.handleLoad (C:\Users\Caspar\AppData\Local\Programs\imapsyncclient\resources\app.asar\node_modules\axios\lib\adapters\xhr.js:77:7)

I have tried the migration with an online Migrator (https://i005.lamiral.info/X/) and there the migration with exactly the same credentials seem to work well.

Please let me know what I can do to solve this.
Btw, 
1. Firewall allows ImapSyncClient 
2 the API Status on the About tab is red

**Comment by ridaamirini** [comment]
Hello @CasparMenke,

I think i need to setup a new API-Server. I try to fix it at the weekend.
